### ISSUE TITLE
Spotify has deprecated web Apis audio features

### ISSUE THREAD

**Issue by sedado22** [NiklasReiche/ad-spotify-mood-lights-sync#17]
Hello. 
[Here ](https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api)it says that they've deprecated the audio-features apis  so if you're having this issue :

` {'data': {'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'spotify_mood_lights_sync', 'message': 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/spotipy/client.py", line 275, in _internal_call\n    response.raise_for_status()\n  File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/audio-features/?ids=1LC2Hcgf2RgEbxPHNTnzaC\n\nDuring handling of the above exception, another exception occurred`

You know who to thank for.. 

Thanks a lot to the developers that made this awesome integration and put a lot of love and effort on this.

**Comment by NiklasReiche** [comment]
Thanks for the heads-up. Looks like this project is dead then. Maybe some alternative service will emerge that I could use, but I doubt that there's anything close to Spotify's dataset.
